name: tile2vec
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - gdal
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - imageio
  - tqdm
  - rasterio
  - scipy
  - seaborn

